GET http://localhost:3000/task HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NTMxOGU3MDg4YWM4NzgxNDY3MGM5MyIsImlhdCI6MTczMzUxMjA4OSwiZXhwIjoxNzMzNTk4NDg5fQ.cnrFExDfzsULwlJqH7OAn7f4fR4FY0wZ6YjZ-IaOHBs

###

POST http://localhost:3000/task HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NTMxOGU3MDg4YWM4NzgxNDY3MGM5MyIsImlhdCI6MTczMzUxMjA4OSwiZXhwIjoxNzMzNTk4NDg5fQ.cnrFExDfzsULwlJqH7OAn7f4fR4FY0wZ6YjZ-IaOHBs
Content-Type: application/json

{
  "title": "Task 1",
  "description": "Description 1",
  "status": "pending"
}


###

GET http://localhost:3000/task/67534f215200de14e8aafa43 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NTMxOGU3MDg4YWM4NzgxNDY3MGM5MyIsImlhdCI6MTczMzUxMjA4OSwiZXhwIjoxNzMzNTk4NDg5fQ.cnrFExDfzsULwlJqH7OAn7f4fR4FY0wZ6YjZ-IaOHBs
